### ISSUE TITLE
Finalizing anatomical processing

### ISSUE THREAD

**Issue by mgxd** [poldracklab/fmriprep-rodents#12]
cc @eilidhmacnicol - After #11 (and a lingering commit f89f1a3), the anatomical pipeline is close to working with the `Fischer344` template. The remaining steps (at least clear to me now) to consider here:

-----------

Registration in the normalization pipeline is failing - perhaps the parameters needs to be synchronized with what's being used in nirodents?
https://github.com/poldracklab/fmriprep-rodents/blob/f89f1a30a7785a39a325ade1f6414cb10b8dc1f9/fmriprep_rodents/patch/workflows/anatomical.py#L543-L545

------------

The tissue probability maps are being calculated with FSL's FAST (the default through the non-freesurfer pathway). Rather, we can probably leverage the Fischer template's `probseg`s and apply them to the anatomical space.

**Comment by eilidhmacnicol** [comment]
The lingering commit is still running on circleCI, but looking at `test_rodent_anat` report generated from the PR yesterday, it seems that the registration is still using `MNI152NLin2009cAsym` as the template, although I'm not sure how the reports are generated so that might just be a typo. 

I can't find where the registration parameters are generated. Specifically,  I can't see where the number of syn stages etc are called. I can see that some of the parameters are in ` RobustMNINormalization`, and an `affine.json`, but can't compare the call. 

Yes, definitely think that we will need to use template probability maps. I am a little impressed by the FAST results generated for the report, but I think using a priori information would be worth it.

**Comment by mgxd** [comment]
The registration parameters are loaded from predefined settings files, see
https://github.com/nipreps/niworkflows/blob/df77431a26fa3f3e4b2aff790fa3b4b2c41dd650/niworkflows/interfaces/mni.py#L139-L158

Although thinking about this some more, it could be better to just replace the `RobustMNINormalization` with a pure `Registration` node to avoid all this tinkering (cc @oesteban).

**Comment by eilidhmacnicol** [comment]
Ah - those were the json files I was looking for... (just in the wrong project). 

There's nothing obviously incompatible with those configuration files, so I will see how the most recent commit goes and start looking into it from there.

**Comment by mgxd** [comment]
looks like the anatomical pipeline stopped smoking..

https://373-278421401-gh.circle-artifacts.com/0/tmp/rodent-se-anat/derivatives/fmriprep-rodents/sub-01.html

**Comment by oesteban** [comment]
I can confirm that the anatomical workflow runs to the end both locally and in the new CircleCI settings I bumped up yesterday. Closing this. Great job folks! and special thanks to @mgxd for the baseline work that has enabled this.
